### ISSUE TITLE
v2.1 and v2.0

### ISSUE THREAD

**Issue by fi0** [snowplow/snowplow-golang-tracker#33]
https://github.com/snowplow/snowplow-golang-tracker/blob/v2.1.0/go.mod#L13

Does this prevent v2.1 to be installed?

**Comment by jbeemster** [comment]
It does - this is a bug introduced by the addition of the stress testing tool.  Will be fixed in v2.2.0.

**Comment by jbeemster** [comment]
Hi @fi0 this has now been fixed - as per your other ticket please change the import line to:

> "github.com/snowplow/snowplow-golang-tracker/v2/tracker"
