### ISSUE TITLE
go module fails

### ISSUE THREAD

**Issue by fi0** [snowplow/snowplow-golang-tracker#34]
github.com/snowplow/snowplow-golang-tracker/tracker imports
	github.com/twinj/uuid tested by
	github.com/twinj/uuid.test imports
	gopkg.in/stretchr/testify.v1/assert: cannot find module providing package gopkg.in/stretchr/testify.v1/assert

**Comment by jbeemster** [comment]
Hi @fi0 apologies for the delay in getting back to you - indeed there are a few issues with the go mod setup at the moment which are being addressed in 2.2.0.

**Comment by jbeemster** [comment]
Hi @fi0 this has now been fixed - if you change your import line to look like the following it should successfully pull in the latest code via go modules:

> "github.com/snowplow/snowplow-golang-tracker/v2/tracker"
