### ISSUE TITLE
Replace myesui/uuid with google/uuid

### ISSUE THREAD

**Issue by ChrisPenner** [snowplow/snowplow-golang-tracker#59]
**Describe the bug**
This project depends on https://github.com/myesui/uuid ; which appears to have disappeared from the face of Github. The repo 404's and the user themself was apparently created only a week ago? Very strange.

```
> go mod vendor
go: github.com/snowplow/snowplow-golang-tracker/v2@v2.0.0-20201008204249-2caa93314ceb requires
        github.com/myesui/uuid@v1.0.0: reading github.com/myesui/uuid/go.mod at revision v1.0.0: unknown revision v1.0.0
```

**To Reproduce**
Depend on `snowplow/snowplow-golang-tracker` and run `go mod vendor`

**Expected behavior**
Don't depend on non-existent projects

---

Obviously this isn't your fault, and maybe that repo will come back? Not sure what's going on, but it may be worthwhile depending on a more reliable uuid package regardless. Cheers!

**Comment by jbeemster** [comment]
Hi @ChrisPenner thanks for the report!  It looks like a dependency of a dependency as we are using twinj in the direct references within the library where we need a UUID.  Will have to see where this transitive dep is coming in from..

**Comment by jredl-va** [comment]
I feel we need to use a different uuid framework:

![image](https://user-images.githubusercontent.com/2300103/107261138-9066c600-6a04-11eb-894c-c51571eabfc5.png)

Would you be open to a pull request that uses: https://github.com/google/uuid

**Comment by jbeemster** [comment]
Hi @jredl-va - PR's are always welcome!  Using something non-archived and maintained is definitely a better option...

**Comment by dmateus** [comment]
Hi @jbeemster - I'm backend engineer at https://github.com/getground. We're using this library and would love to PR this change: `replace myesui/uuid with google/uuid`

Do I need repo permissions? Also do I need to sign a CLA?

**Comment by paulboocock** [comment]
Hey @dmateus 
Thanks for reaching out. You don't need any particular permissions for this, you can fork the repository, make your changes and then open a PR from your fork into master. 
When you open the PR, a bot will pop up that will ask you to complete the CLA and then add a comment to tell the bot you've done it. Once thats done, we can look at merging the PR and getting a release out. I should have time to do this reasonably soon, probably early next week.
